spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update


server:
  port: 8081

#person:
#  name: 张三
#  age: 18
#  birth: 1995/05/12
#  id: 1452588544
#  email: 'djhs@qq.com'
#  pets:
#    - cat
#    - dog
#    - pig
#  map:
#    name: aaaa
#    demo: 12
#    p: [1,2,3,4]
#  dept:
#    name: 开发部
#    code: 111
